eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8801/eureka/
server:
  port: 8802
spring:
  redis:
    database: 0
    port: 6379
    timeout: 30000
    host: 127.0.0.1
    password: 123456
  datasource:
    test01:
      url: jdbc:mysql://localhost:3306/test01?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&useSSL=true
      username: root
      password: 123456
      driverClassName: com.mysql.cj.jdbc.Driver
    test02:
      url: jdbc:mysql://localhost:3306/test02?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&useSSL=true
      username: root
      password: 123456
      driverClassName: com.mysql.cj.jdbc.Driver
    test03:
      url: jdbc:mysql://localhost:3306/test_redis?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&useSSL=true
      username: root
      password: 123456
      driverClassName: com.mysql.cj.jdbc.Driver
  application:
     name: cloud-provider
logging:
  level:
    com.cloud.provider.dao: debug
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000
# 定时任务配置, 默认同步
IS_SYNC: false
# 缓存
# value和失效时间分隔符
myCache.separator: #
# 自定义缓存失效时间扫包范围
myCache.packageName: com.testalipay.demo

