eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8801/eureka/
server:
  port: 8802
spring:
  redis:
    database: 0
    port: 6379
    timeout: 30000
    host: 127.0.0.1
  datasource:
    url: jdbc:mysql://localhost:3306/test_redis?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 123456
    driverClassName: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
mybatis:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.test.redisdemo.entity
logging:
  level:
    com.test.redisdemo.dao: debug
  application:
    name: cloud-provider
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000

